extends: airbnb
globals:
  window: true
  document: true
rules:
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
overrides: [
  {
    files: ["*.js"];
      rules: {
        no-unused-expressions: "off"
      }
  }
]
parser: "babel-eslint"